using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using Inscribed.Application.Contracts.Schemas;

namespace Inscribed.Application.Services.Policies;

public static class FileCollectionPolicyLoader
{
    private static readonly Regex KeyPattern = new("^[a-z0-9]+(-[a-z0-9]+)*$", RegexOptions.Compiled);
    private static readonly Regex FieldNamePattern = new("^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.Compiled);

    private static readonly JsonSerializerOptions SerializerOptions = new(JsonSerializerDefaults.Web)
    {
        UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
        Converters = { new JsonStringEnumConverter(allowIntegerValues: false) },
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true,
    };

    public static IReadOnlyList<FileCollectionPolicy> Load(string directory, bool required)
    {
        if (!Directory.Exists(directory))
        {
            if (required)
                throw new InvalidOperationException($"Collections path '{directory}' does not exist.");

            return [];
        }

        var errors = new List<string>();
        var policies = new List<FileCollectionPolicy>();
        var sources = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (var file in Directory.GetFiles(directory, "*.json").OrderBy(Path.GetFileName, StringComparer.Ordinal))
        {
            var fileName = Path.GetFileName(file);

            CollectionDefinitionDocument? document;
            try
            {
                document = JsonSerializer.Deserialize<CollectionDefinitionDocument>(File.ReadAllText(file), SerializerOptions);
            }
            catch (JsonException ex)
            {
                errors.Add($"{fileName}: invalid JSON: {ex.Message}");
                continue;
            }

            if (document is null)
            {
                errors.Add($"{fileName}: definition is empty");
                continue;
            }

            var fileErrors = new List<string>();
            var policy = BuildPolicy(document, fileName, fileErrors);

            if (policy is not null && sources.TryGetValue(policy.Key, out var otherFile))
                fileErrors.Add($"duplicate collection key '{policy.Key}', already defined in '{otherFile}'");

            if (fileErrors.Count > 0)
            {
                errors.AddRange(fileErrors.Select(e => $"{fileName}: {e}"));
                continue;
            }

            sources.Add(policy!.Key, fileName);
            policies.Add(policy);
        }

        if (errors.Count > 0)
            throw new InvalidOperationException(
                $"Invalid collection definition(s) in '{directory}':{Environment.NewLine}" +
                string.Join(Environment.NewLine, errors.Select(e => $"  - {e}")));

        return policies;
    }

    private static FileCollectionPolicy? BuildPolicy(CollectionDefinitionDocument document, string fileName, List<string> errors)
    {
        if (string.IsNullOrWhiteSpace(document.Key))
            errors.Add("'key' is required");
        else if (!KeyPattern.IsMatch(document.Key))
            errors.Add($"key '{document.Key}' must be lowercase alphanumerics separated by single hyphens (e.g. 'team-members')");

        var fields = BuildFields(document.Fields, "fields", errors);

        var slugSource = SlugSource.UserDefined;
        string? slugSourceField = null;

        if (document.Slug is { } slug)
        {
            if (slug.Source is null)
            {
                errors.Add("'slug.source' is required and must be 'UserDefined' or 'AutoGenerated'");
            }
            else if (slug.Source == SlugSource.AutoGenerated)
            {
                slugSource = SlugSource.AutoGenerated;

                if (string.IsNullOrWhiteSpace(slug.From))
                {
                    errors.Add("'slug.from' is required when 'slug.source' is 'AutoGenerated'");
                }
                else if (fields is not null)
                {
                    var source = fields.FirstOrDefault(f => string.Equals(f.Name, slug.From, StringComparison.OrdinalIgnoreCase));

                    if (source is null)
                        errors.Add($"'slug.from' references unknown field '{slug.From}'");
                    else if (source.Type is not (FieldType.Text or FieldType.ShortText))
                        errors.Add($"'slug.from' field '{slug.From}' must be of type Text or ShortText, not {source.Type}");
                    else
                        slugSourceField = source.Name;
                }
            }
            else if (slug.From is not null)
            {
                errors.Add("'slug.from' is only valid when 'slug.source' is 'AutoGenerated'");
            }
        }

        if (errors.Count > 0 || fields is null)
            return null;

        return new FileCollectionPolicy(
            document.Key!,
            new CollectionSchema(fields),
            slugSource,
            slugSourceField,
            document.AllowAnonymousRead,
            fileName);
    }

    private static List<FieldDefinition>? BuildFields(List<FieldDefinitionDocument>? documents, string path, List<string> errors)
    {
        if (documents is null || documents.Count == 0)
        {
            errors.Add($"'{path}' must contain at least one field");
            return null;
        }

        var errorsBefore = errors.Count;
        var names = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        var fields = new List<FieldDefinition>(documents.Count);

        for (var i = 0; i < documents.Count; i++)
        {
            var document = documents[i];
            var fieldErrorsBefore = errors.Count;
            var fieldRef = string.IsNullOrWhiteSpace(document.Name) ? $"'{path}[{i}]'" : $"field '{document.Name}'";

            if (string.IsNullOrWhiteSpace(document.Name))
                errors.Add($"{fieldRef}: 'name' is required");
            else if (!FieldNamePattern.IsMatch(document.Name))
                errors.Add($"{fieldRef}: field names must start with a letter or underscore and contain only letters, digits, and underscores");
            else if (!names.Add(document.Name))
                errors.Add($"{fieldRef}: duplicate field name");

            if (document.Type is null)
                errors.Add($"{fieldRef}: 'type' is required");

            List<FieldDefinition>? itemFields = null;

            if (document.Type == FieldType.ObjectArray)
                itemFields = BuildFields(document.ItemFields, $"{path}[{i}].itemFields", errors);
            else if (document.ItemFields is not null)
                errors.Add($"{fieldRef}: 'itemFields' is only valid for ObjectArray fields");

            if (errors.Count > fieldErrorsBefore)
                continue;

            fields.Add(new FieldDefinition(
                document.Name!,
                document.Type!.Value,
                string.IsNullOrWhiteSpace(document.Label) ? document.Name! : document.Label,
                document.Required,
                document.Help,
                document.ReadOnly,
                document.Filterable,
                document.Options,
                itemFields));
        }

        return errors.Count == errorsBefore ? fields : null;
    }
}