using System.Security.Claims;
using System.Text.Json.Nodes;
using Inscribed.Application.Contracts.Policies;
using Inscribed.Application.Contracts.Schemas;

namespace Inscribed.Application.Services.Policies;

public sealed class NewsCollectionPolicy : ICollectionPolicy
{
    public string Key => "news";

    public SlugSource SlugSource => SlugSource.AutoGenerated;

    public bool AllowAnonymousRead => true;

    public string? GetSlugSourceValue(JsonNode data) => data["title"]?.GetValue<string>();

    public CollectionSchema Schema { get; } = new([
        new("title", FieldType.Text, "Başlık", Required: true),
        new("summary", FieldType.Text, "Özet"),
        new("body", FieldType.RichText, "İçerik", Required: true),
        new("heroImage", FieldType.Url, "Kapak Görseli"),
        new("tags", FieldType.StringArray, "Etiketler", Filterable: true),
        new("author", FieldType.Text, "Yazar", Filterable: true),
        new("featured", FieldType.Bool, "Öne Çıkar", Filterable: true),
    ]);

    public bool CanEdit(ClaimsPrincipal user, string slug) => true;

    public Task<JsonNode> EnrichAsync(string slug, JsonNode data, CancellationToken cancellationToken = default)
        => Task.FromResult(data);
}
