using System.Security.Claims;
using System.Text.Json.Nodes;
using Skylab.Cms.Application.Contracts.Repositories;
using Skylab.Cms.Application.Contracts.Requests;
using Skylab.Cms.Application.Contracts.Responses;
using Skylab.Cms.Application.Contracts.Schemas;
using Skylab.Cms.Application.Services.Helpers;
using Skylab.Cms.Application.Services.Policies;
using Skylab.Cms.Domain.Entities;
using Skylab.Cms.Domain.Enums;
using Skylab.Cms.Domain.Exceptions;

namespace Skylab.Cms.Application.Services;

public sealed class CollectionService : ICollectionService
{
    private readonly ICollectionItemRepository _repository;
    private readonly ICollectionPolicyResolver _policyResolver;

    public CollectionService(ICollectionItemRepository repository, ICollectionPolicyResolver policyResolver)
    {
        _repository = repository;
        _policyResolver = policyResolver;
    }

    public CollectionSchema GetSchema(CollectionKey key)
        => _policyResolver.Resolve(key).Schema;

    public IReadOnlyList<MyCollectionResponse> GetMyCollections(ClaimsPrincipal user)
    {
        var result = new List<MyCollectionResponse>();
        foreach (var policy in _policyResolver.All)
        {
            var canCreate = policy.CanCreate(user);
            var hasEditableVirtual = policy.GetVirtualSlugs(user).Count > 0;

            if (!canCreate && !hasEditableVirtual)
                continue;

            result.Add(new MyCollectionResponse(
                CollectionKey: policy.Key.ToString(),
                Schema: policy.Schema,
                CanCreate: canCreate,
                SlugSource: policy.SlugSource.ToString()
            ));
        }
        return result;
    }

    public async Task<PagedListResponse<CollectionItemResponse>> ListAsync(
        CollectionKey key,
        ClaimsPrincipal user,
        IDictionary<string, string>? filters,
        int offset,
        int limit,
        CancellationToken cancellationToken = default)
    {
        var policy = _policyResolver.Resolve(key);

        var filterJson = filters is { Count: > 0 }
            ? CollectionFilterParser.Build(policy.Schema, filters)
            : null;

        var (items, total) = await _repository.ListPagedAsync(key, filterJson, offset, limit, cancellationToken);

        var responses = new List<CollectionItemResponse>(items.Count);
        var existingSlugs = new HashSet<string>(StringComparer.Ordinal);

        foreach (var item in items)
        {
            var enriched = await policy.EnrichAsync(item.Slug, item.Data, cancellationToken);
            responses.Add(ToResponse(item, enriched, policy.CanEdit(user, item.Slug)));
            existingSlugs.Add(item.Slug);
        }

        if (filterJson is null && offset == 0)
        {
            foreach (var virtualSlug in policy.GetVirtualSlugs(user))
            {
                if (existingSlugs.Contains(virtualSlug)) continue;

                var empty = new JsonObject();
                var enriched = await policy.EnrichAsync(virtualSlug, empty, cancellationToken);
                responses.Add(new CollectionItemResponse(
                    Id: Guid.Empty,
                    CollectionKey: key.ToString(),
                    Slug: virtualSlug,
                    Data: enriched,
                    Version: 0,
                    CanEdit: true
                ));
            }
        }

        return new PagedListResponse<CollectionItemResponse>(responses, total, offset, limit);
    }

    public async Task<CollectionItemResponse?> GetAsync(CollectionKey key, string slug, ClaimsPrincipal user, CancellationToken cancellationToken = default)
    {
        var normalizedSlug = SlugNormalizer.NormalizeBlockPath(slug);
        var policy = _policyResolver.Resolve(key);

        var item = await _repository.GetBySlugAsync(key, normalizedSlug, cancellationToken: cancellationToken);
        if (item is null) return null;

        var enriched = await policy.EnrichAsync(item.Slug, item.Data, cancellationToken);
        return ToResponse(item, enriched, policy.CanEdit(user, item.Slug));
    }

    public async Task<CollectionItemResponse> UpsertAsync(CollectionKey key, string slug, UpsertCollectionItemRequest request, ClaimsPrincipal user, string updatedBy, CancellationToken cancellationToken = default)
    {
        var normalizedSlug = SlugNormalizer.NormalizeBlockPath(slug);
        var policy = _policyResolver.Resolve(key);

        if (!policy.CanEdit(user, normalizedSlug))
            throw new UnauthorizedAccessException($"User cannot edit '{key}/{normalizedSlug}'.");

        var validated = CollectionSchemaValidator.ValidateAndStrip(policy.Schema, request.Data);

        var utcNow = DateTime.UtcNow;
        var item = await _repository.GetBySlugAsync(key, normalizedSlug, cancellationToken: cancellationToken);

        if (item is null)
        {
            if (policy.SlugSource == SlugSource.AutoGenerated)
                throw new ValidationException([$"Collection '{key}' uses auto-generated slugs; use POST to create items."]);

            if (!policy.CanCreate(user) && !policy.GetVirtualSlugs(user).Contains(normalizedSlug))
                throw new UnauthorizedAccessException($"User cannot create new items in '{key}'.");

            item = CollectionItem.Create(key, normalizedSlug, validated, updatedBy, utcNow);
            await _repository.AddAsync(item, cancellationToken);
        }
        else
        {
            if (request.Version is { } v && v != item.Version)
                throw new ConcurrencyConflictException($"Version conflict on '{key}/{normalizedSlug}'. Expected {item.Version}, got {v}.");

            item.UpdateData(validated, updatedBy, utcNow);
        }

        await _repository.SaveChangesAsync(cancellationToken);

        var enriched = await policy.EnrichAsync(item.Slug, item.Data, cancellationToken);
        return ToResponse(item, enriched, canEdit: true);
    }

    public async Task<CollectionItemResponse> CreateAutoSlugAsync(CollectionKey key, CreateCollectionItemRequest request, ClaimsPrincipal user, string updatedBy, CancellationToken cancellationToken = default)
    {
        var policy = _policyResolver.Resolve(key);

        if (policy.SlugSource != SlugSource.AutoGenerated)
            throw new ValidationException([$"Collection '{key}' does not use auto-generated slugs; use PUT with a slug."]);

        if (!policy.CanCreate(user))
            throw new UnauthorizedAccessException($"User cannot create new items in '{key}'.");

        var validated = CollectionSchemaValidator.ValidateAndStrip(policy.Schema, request.Data);

        var source = policy.GetSlugSourceValue(validated);
        if (string.IsNullOrWhiteSpace(source))
            throw new ValidationException(["Slug source field is missing or empty."]);

        var baseSlug = SlugGenerator.Slugify(source);
        if (string.IsNullOrWhiteSpace(baseSlug))
            throw new ValidationException(["Slug source produced an empty slug."]);

        var slug = await ResolveUniqueSlugAsync(key, baseSlug, cancellationToken);

        var utcNow = DateTime.UtcNow;
        var item = CollectionItem.Create(key, slug, validated, updatedBy, utcNow);
        await _repository.AddAsync(item, cancellationToken);
        await _repository.SaveChangesAsync(cancellationToken);

        var enriched = await policy.EnrichAsync(item.Slug, item.Data, cancellationToken);
        return ToResponse(item, enriched, canEdit: true);
    }

    private async Task<string> ResolveUniqueSlugAsync(CollectionKey key, string baseSlug, CancellationToken cancellationToken)
    {
        var candidate = baseSlug;
        var n = 2;
        while (await _repository.GetBySlugAsync(key, candidate, includeArchived: true, cancellationToken: cancellationToken) is not null)
        {
            candidate = $"{baseSlug}-{n++}";
        }
        return candidate;
    }

    private static CollectionItemResponse ToResponse(CollectionItem item, JsonNode data, bool canEdit) =>
        new(
            Id: item.Id,
            CollectionKey: item.CollectionKey.ToString(),
            Slug: item.Slug,
            Data: data,
            Version: item.Version,
            CanEdit: canEdit
        );
}